# Created with WinGet Releaser v2 using Komac v1.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: pizzaboxer.Bloxstrap
PackageVersion: 2.1.1
PackageLocale: en-US
Publisher: pizzaboxer
PublisherUrl: https://pizzaboxer.xyz
PublisherSupportUrl: https://github.com/pizzaboxer/bloxstrap/issues
PackageName: Bloxstrap
PackageUrl: https://github.com/pizzaboxer/bloxstrap
License: MIT
LicenseUrl: https://github.com/pizzaboxer/bloxstrap/blob/main/LICENSE
Copyright: Copyright (c) 2022 pizzaboxer
CopyrightUrl: https://github.com/pizzaboxer/bloxstrap/blob/main/LICENSE
ShortDescription: An open-source, feature-packed alternative bootstrapper for Roblox.
Tags:
- launcher
- mod
- player
- rbxfpsunlocker
- roblox
ReleaseNotes: |-
  - Roblox is reinstalled if the files for it don't exist.
    Not a critical issue, but it's just better to get this out earlier. (#128)
  - WebView2 support has been added.
    It's not yet released, but it's currently being tested on ZIntegration, This fixes anyone having problems with that. (#131)
  - Bloxstrap now checks for alternative Roblox download mirrors.
    This is in response to a bunch of ISPs deciding to block Roblox's main download mirror today. (#134)
ReleaseNotesUrl: https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.1.1
ManifestType: defaultLocale
ManifestVersion: 1.4.0
