# Created with WinGet Releaser v2 using Komac v1.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: pizzaboxer.Bloxstrap
PackageVersion: 2.1.1
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -quiet -nolaunch
  SilentWithProgress: -quiet -nolaunch
  Upgrade: -upgrade
UpgradeBehavior: install
Protocols:
- roblox
- roblox-player
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
ReleaseDate: 2023-04-16
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/pizzaboxer/bloxstrap/releases/download/v2.1.1/Bloxstrap-v2.1.1-x86.exe
  InstallerSha256: A693CFCAEBB425011B501EE0E4B39397ACC225BAFE2F7E991297A3AE7291880C
- Architecture: x64
  InstallerUrl: https://github.com/pizzaboxer/bloxstrap/releases/download/v2.1.1/Bloxstrap-v2.1.1-x64.exe
  InstallerSha256: 4BD9E141F475D52A6F51D0B5CED391BFAD4CB173F8AC6EBAFC87F70CB28A2B87
ManifestType: installer
ManifestVersion: 1.4.0
